version: '2'
services:
  mongo:
    image: mongo:3
    ports:
      - '27017:27017'
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app:rw
    ports:
      - '5000:5000'
      - '3000:3000'
    links:
      - mongo
    command: >
        sh -c '
         cd /usr/app &&
         npm install &&
         npm run config-docker &&
         npm run build-builder &&
         npm run dev
        '