version: '2'
services:
  mongo:
    image: mongo:3
    networks:
      - app_net
    ports:
      - '27017:27017'
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    links:
      - mongo
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - web
      - mongo
    links:
      - mongo
    networks:
      - app_net
    extra_hosts:
      - "api.tny.local:172.16.238.10"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1